//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taniguchi_Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public int Invoice_Id { get; set; }
        public string Product_Code { get; set; }
        public decimal Unit_Price { get; set; }
        public int Quantity { get; set; }
        public decimal Item_Total { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
