//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taniguchi_Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOption
    {
        public decimal Sales_Tax_Rate { get; set; }
        public decimal First_Book_Ship_Charge { get; set; }
        public decimal Additional_Book_Ship_Charge { get; set; }
        public bool Is_Deleted { get; set; }
    }
}
