//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taniguchi_Final_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public decimal Unit_Price { get; set; }
        public int On_Hand_Quantity { get; set; }
        public bool Is_Deleted { get; set; }
    
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
    }
}
